name: "\U0001F41E Report a problem"
description: "Report a problem with ESLint JS language tools"
title: "Bug: (fill in)"
labels:
    - bug
    - "repro:needed"
body:
    - type: checkboxes
      attributes:
          label: Which packages are affected?
          options:
              - label: "`espree`"
                required: false
              - label: "`eslint-scope`"
                required: false
              - label: "`eslint-visitor-keys`"
                required: false
    - type: textarea
      attributes:
          label: Environment
          description: |
              Please provide the following information:
          value: |
              Node version:
              npm version:
              ESLint version:
              Operating System:
      validations:
          required: true
    - type: textarea
      attributes:
          label: What did you do?
      validations:
          required: true
    - type: textarea
      attributes:
          label: What did you expect to happen?
      validations:
          required: true
    - type: textarea
      attributes:
          label: What actually happened?
      validations:
          required: true
    - type: input
      attributes:
          label: Link to Minimal Reproducible Example
          description: "Link to a [StackBlitz](https://stackblitz.com) or GitHub repo with a minimal reproduction of the problem. **A minimal reproduction is required** so that others can help debug your issue. If a report is vague (e.g. just a generic error message) and has no reproduction, it may be auto-closed."
          placeholder: "https://stackblitz.com/abcd1234"
      validations:
          required: true
    - type: checkboxes
      attributes:
          label: Participation
          options:
              - label: I am willing to submit a pull request for this issue.
                required: false
    - type: markdown
      attributes:
          value: Please **do not** open a pull request until this issue has been accepted by the team.
    - type: checkboxes
      attributes:
          label: AI acknowledgment
          options:
              - label: I did not use AI to generate this issue report.
                required: false
              - label: (If the above is not checked) I have reviewed the AI-generated content before submitting.
                required: false
    - type: textarea
      attributes:
          label: Additional comments
          description: Is there anything else you'd like to mention?
