/* eslint-disable jsdoc/valid-types -- doesn't allow `readonly`.
   TODO: remove eslint-disable when https://github.com/jsdoc-type-pratt-parser/jsdoc-type-pratt-parser/issues/164 is fixed
*/
/**
 * @typedef {{ readonly [type: string]: ReadonlyArray<string> }} VisitorKeys
 */
/* eslint-enable jsdoc/valid-types -- doesn't allow `readonly string[]`. TODO: check why */

/**
 * @type {VisitorKeys}
 */
const KEYS = Object.freeze({
	ArrayExpression: Object.freeze(["elements"]),
	ArrayPattern: Object.freeze(["elements"]),
	ArrowFunctionExpression: Object.freeze(["params", "body"]),
	AssignmentExpression: Object.freeze(["left", "right"]),
	AssignmentPattern: Object.freeze(["left", "right"]),
	AwaitExpression: Object.freeze(["argument"]),
	BinaryExpression: Object.freeze(["left", "right"]),
	BlockStatement: Object.freeze(["body"]),
	BreakStatement: Object.freeze(["label"]),
	CallExpression: Object.freeze(["callee", "arguments"]),
	CatchClause: Object.freeze(["param", "body"]),
	ChainExpression: Object.freeze(["expression"]),
	ClassBody: Object.freeze(["body"]),
	ClassDeclaration: Object.freeze(["id", "superClass", "body"]),
	ClassExpression: Object.freeze(["id", "superClass", "body"]),
	ConditionalExpression: Object.freeze(["test", "consequent", "alternate"]),
	ContinueStatement: Object.freeze(["label"]),
	DebuggerStatement: Object.freeze([]),
	DoWhileStatement: Object.freeze(["body", "test"]),
	EmptyStatement: Object.freeze([]),
	ExperimentalRestProperty: Object.freeze(["argument"]),
	ExperimentalSpreadProperty: Object.freeze(["argument"]),
	ExportAllDeclaration: Object.freeze(["exported", "source", "attributes"]),
	ExportDefaultDeclaration: Object.freeze(["declaration"]),
	ExportNamedDeclaration: Object.freeze([
		"declaration",
		"specifiers",
		"source",
		"attributes",
	]),
	ExportSpecifier: Object.freeze(["local", "exported"]),
	ExpressionStatement: Object.freeze(["expression"]),
	ForInStatement: Object.freeze(["left", "right", "body"]),
	ForOfStatement: Object.freeze(["left", "right", "body"]),
	ForStatement: Object.freeze(["init", "test", "update", "body"]),
	FunctionDeclaration: Object.freeze(["id", "params", "body"]),
	FunctionExpression: Object.freeze(["id", "params", "body"]),
	Identifier: Object.freeze([]),
	IfStatement: Object.freeze(["test", "consequent", "alternate"]),
	ImportAttribute: Object.freeze(["key", "value"]),
	ImportDeclaration: Object.freeze(["specifiers", "source", "attributes"]),
	ImportDefaultSpecifier: Object.freeze(["local"]),
	ImportExpression: Object.freeze(["source", "options"]),
	ImportNamespaceSpecifier: Object.freeze(["local"]),
	ImportSpecifier: Object.freeze(["imported", "local"]),
	JSXAttribute: Object.freeze(["name", "value"]),
	JSXClosingElement: Object.freeze(["name"]),
	JSXClosingFragment: Object.freeze([]),
	JSXElement: Object.freeze(["openingElement", "children", "closingElement"]),
	JSXEmptyExpression: Object.freeze([]),
	JSXExpressionContainer: Object.freeze(["expression"]),
	JSXFragment: Object.freeze([
		"openingFragment",
		"children",
		"closingFragment",
	]),
	JSXIdentifier: Object.freeze([]),
	JSXMemberExpression: Object.freeze(["object", "property"]),
	JSXNamespacedName: Object.freeze(["namespace", "name"]),
	JSXOpeningElement: Object.freeze(["name", "attributes"]),
	JSXOpeningFragment: Object.freeze([]),
	JSXSpreadAttribute: Object.freeze(["argument"]),
	JSXSpreadChild: Object.freeze(["expression"]),
	JSXText: Object.freeze([]),
	LabeledStatement: Object.freeze(["label", "body"]),
	Literal: Object.freeze([]),
	LogicalExpression: Object.freeze(["left", "right"]),
	MemberExpression: Object.freeze(["object", "property"]),
	MetaProperty: Object.freeze(["meta", "property"]),
	MethodDefinition: Object.freeze(["key", "value"]),
	NewExpression: Object.freeze(["callee", "arguments"]),
	ObjectExpression: Object.freeze(["properties"]),
	ObjectPattern: Object.freeze(["properties"]),
	PrivateIdentifier: Object.freeze([]),
	Program: Object.freeze(["body"]),
	Property: Object.freeze(["key", "value"]),
	PropertyDefinition: Object.freeze(["key", "value"]),
	RestElement: Object.freeze(["argument"]),
	ReturnStatement: Object.freeze(["argument"]),
	SequenceExpression: Object.freeze(["expressions"]),
	SpreadElement: Object.freeze(["argument"]),
	StaticBlock: Object.freeze(["body"]),
	Super: Object.freeze([]),
	SwitchCase: Object.freeze(["test", "consequent"]),
	SwitchStatement: Object.freeze(["discriminant", "cases"]),
	TaggedTemplateExpression: Object.freeze(["tag", "quasi"]),
	TemplateElement: Object.freeze([]),
	TemplateLiteral: Object.freeze(["quasis", "expressions"]),
	ThisExpression: Object.freeze([]),
	ThrowStatement: Object.freeze(["argument"]),
	TryStatement: Object.freeze(["block", "handler", "finalizer"]),
	UnaryExpression: Object.freeze(["argument"]),
	UpdateExpression: Object.freeze(["argument"]),
	VariableDeclaration: Object.freeze(["declarations"]),
	VariableDeclarator: Object.freeze(["id", "init"]),
	WhileStatement: Object.freeze(["test", "body"]),
	WithStatement: Object.freeze(["object", "body"]),
	YieldExpression: Object.freeze(["argument"]),
});

export default KEYS;
